[project]
name = "simple-crowdfunding"
clarity_version = "1.0"
description = "A simple crowdfunding smart contract on the Stacks blockchain."
authors = ["Hammed Yakub <hamsohood@gmail.com>"]
license = "MIT"

[contracts.crowdfunding]
path = "contracts/crowdfunding.clar"

[repl.analysis]
passes = ["check_checker"]
